import 'package:equatable/equatable.dart';

/// The parsed result of intent detection on a raw command string.
class CommandIntent extends Equatable {
  final IntentType type;
  final String? targetAppName; // For OPEN_APP
  final String? targetContact; // For MAKE_CALL
  final String? url; // For OPEN_URL
  final String? searchQuery; // For YOUTUBE_SEARCH
  final String? targetSetting; // For OPEN_SETTINGS
  final String rawText;
  final String? replyText; // Conversational reply generated by AI
  final List<CommandIntent> subCommands; // For MULTI_COMMAND

  const CommandIntent({
    required this.type,
    required this.rawText,
    this.targetAppName,
    this.targetContact,
    this.url,
    this.searchQuery,
    this.targetSetting,
    this.replyText,
    this.subCommands = const [],
  });

  factory CommandIntent.fromJson(Map<String, dynamic> json, String rawText) {
    try {
      final String typeString = json['type'] as String? ?? 'unknown';
      IntentType type = IntentType.values.firstWhere(
        (e) => e.name == typeString,
        orElse: () => IntentType.unknown,
      );

      return CommandIntent(
        type: type,
        rawText: rawText,
        targetAppName: json['targetAppName'] as String?,
        targetContact: json['targetContact'] as String?,
        url: json['url'] as String?,
        searchQuery: json['searchQuery'] as String?,
        targetSetting: json['targetSetting'] as String?,
        replyText: json['replyText'] as String?,
      );
    } catch (e) {
      return CommandIntent(type: IntentType.unknown, rawText: rawText);
    }
  }

  @override
  List<Object?> get props => [
        type,
        targetAppName,
        targetContact,
        url,
        searchQuery,
        targetSetting,
        rawText,
        replyText,
      ];
}

enum IntentType {
  openApp,
  makeCall,
  openUrl,
  youtubeSearch,
  reopen,
  multiCommand,
  turnOnFlashlight,
  turnOffFlashlight,
  turnOnWifi,
  turnOffWifi,
  turnOnBluetooth,
  turnOffBluetooth,
  openSettings,
  openCamera,
  generalChat,
  clearChat,
  unknown,
}
